### ISSUE TITLE
error in google colab

### ISSUE THREAD

**Issue by lpinuer** [PradeepSinghMakwana/sheep_tracking#1]
i had a error when a tried to run the example

!python test_on_video.py --video-input video-clip.mp4 --video-output vdo

AssertionError: Please specify detections file.

/usr/local/lib/python3.6/dist-packages/sklearn/utils/linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
Traceback (most recent call last):
  File "test_on_video.py", line 135, in <module>
    assert os.path.isfile(args.input_text_file), "Please specify detections file."
AssertionError: Please specify detections file.

and in the line 
!python sheepFinder.py --config-file detectron2/configs/COCO-Detection/faster_rcnn_R_50F_PN_3x.yaml --video-input video-clip.mp4 --confidence-threshold 0.6 --opts MODEL.WEIGHTS detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl

ImportError: /usr/local/lib/python3.6/dist-packages/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

**Comment by PradeepSinghMakwana** [comment]
Thanks lpinuer, There was some dependency problems which are now fixed in the readme(now using cu101 and pyyaml 5.1).  Can you please try again and let me know if everything is ok.
